# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notif.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotif.proto\x12\x05notif\"`\n\x05Notif\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x14\n\x0c\x66rom_user_id\x18\x04 \x01(\x05\x12\x12\n\nto_user_id\x18\x05 \x01(\x05\"_\n\x10SendNotifRequest\x12\x14\n\x0c\x66rom_user_id\x18\x01 \x01(\x05\x12\x12\n\nto_user_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"l\n\x11SendNotifResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x14\n\x0c\x66rom_user_id\x18\x04 \x01(\x05\x12\x12\n\nto_user_id\x18\x05 \x01(\x05\"#\n\x10GetNotifsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"1\n\x11GetNotifsResponse\x12\x1c\n\x06notifs\x18\x01 \x03(\x0b\x32\x0c.notif.Notif\" \n\x12\x44\x65leteNotifRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"!\n\x13\x44\x65leteNotifResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xd4\x01\n\x0cNotifService\x12>\n\tSendNotif\x12\x17.notif.SendNotifRequest\x1a\x18.notif.SendNotifResponse\x12>\n\tGetNotifs\x12\x17.notif.GetNotifsRequest\x1a\x18.notif.GetNotifsResponse\x12\x44\n\x0b\x44\x65leteNotif\x12\x19.notif.DeleteNotifRequest\x1a\x1a.notif.DeleteNotifResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notif_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIF']._serialized_start=22
  _globals['_NOTIF']._serialized_end=118
  _globals['_SENDNOTIFREQUEST']._serialized_start=120
  _globals['_SENDNOTIFREQUEST']._serialized_end=215
  _globals['_SENDNOTIFRESPONSE']._serialized_start=217
  _globals['_SENDNOTIFRESPONSE']._serialized_end=325
  _globals['_GETNOTIFSREQUEST']._serialized_start=327
  _globals['_GETNOTIFSREQUEST']._serialized_end=362
  _globals['_GETNOTIFSRESPONSE']._serialized_start=364
  _globals['_GETNOTIFSRESPONSE']._serialized_end=413
  _globals['_DELETENOTIFREQUEST']._serialized_start=415
  _globals['_DELETENOTIFREQUEST']._serialized_end=447
  _globals['_DELETENOTIFRESPONSE']._serialized_start=449
  _globals['_DELETENOTIFRESPONSE']._serialized_end=482
  _globals['_NOTIFSERVICE']._serialized_start=485
  _globals['_NOTIFSERVICE']._serialized_end=697
# @@protoc_insertion_point(module_scope)
