# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmember.proto\x12\x06member\"C\n\x06Member\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x13\n\x11MemberListRequest\"5\n\x12MemberListResponse\x12\x1f\n\x07members\x18\x01 \x03(\x0b\x32\x0e.member.Member\"\x1e\n\x10MemberGetRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"<\n\x11MemberGetResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x05\"5\n\x13MemberCreateRequest\x12\x1e\n\x06member\x18\x01 \x01(\x0b\x32\x0e.member.Member\"6\n\x14MemberCreateResponse\x12\x1e\n\x06member\x18\x01 \x01(\x0b\x32\x0e.member.Member\"5\n\x13MemberUpdateRequest\x12\x1e\n\x06member\x18\x01 \x01(\x0b\x32\x0e.member.Member\"6\n\x14MemberUpdateResponse\x12\x1e\n\x06member\x18\x01 \x01(\x0b\x32\x0e.member.Member\"!\n\x13MemberDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x16\n\x14MemberDeleteResponse2\xe3\x02\n\rMemberService\x12?\n\x04List\x12\x19.member.MemberListRequest\x1a\x1a.member.MemberListResponse\"\x00\x12<\n\x03Get\x12\x18.member.MemberGetRequest\x1a\x19.member.MemberGetResponse\"\x00\x12\x45\n\x06\x43reate\x12\x1b.member.MemberCreateRequest\x1a\x1c.member.MemberCreateResponse\"\x00\x12\x45\n\x06Update\x12\x1b.member.MemberUpdateRequest\x1a\x1c.member.MemberUpdateResponse\"\x00\x12\x45\n\x06\x44\x65lete\x12\x1b.member.MemberDeleteRequest\x1a\x1c.member.MemberDeleteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'member_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MEMBER']._serialized_start=24
  _globals['_MEMBER']._serialized_end=91
  _globals['_MEMBERLISTREQUEST']._serialized_start=93
  _globals['_MEMBERLISTREQUEST']._serialized_end=112
  _globals['_MEMBERLISTRESPONSE']._serialized_start=114
  _globals['_MEMBERLISTRESPONSE']._serialized_end=167
  _globals['_MEMBERGETREQUEST']._serialized_start=169
  _globals['_MEMBERGETREQUEST']._serialized_end=199
  _globals['_MEMBERGETRESPONSE']._serialized_start=201
  _globals['_MEMBERGETRESPONSE']._serialized_end=261
  _globals['_MEMBERCREATEREQUEST']._serialized_start=263
  _globals['_MEMBERCREATEREQUEST']._serialized_end=316
  _globals['_MEMBERCREATERESPONSE']._serialized_start=318
  _globals['_MEMBERCREATERESPONSE']._serialized_end=372
  _globals['_MEMBERUPDATEREQUEST']._serialized_start=374
  _globals['_MEMBERUPDATEREQUEST']._serialized_end=427
  _globals['_MEMBERUPDATERESPONSE']._serialized_start=429
  _globals['_MEMBERUPDATERESPONSE']._serialized_end=483
  _globals['_MEMBERDELETEREQUEST']._serialized_start=485
  _globals['_MEMBERDELETEREQUEST']._serialized_end=518
  _globals['_MEMBERDELETERESPONSE']._serialized_start=520
  _globals['_MEMBERDELETERESPONSE']._serialized_end=542
  _globals['_MEMBERSERVICE']._serialized_start=545
  _globals['_MEMBERSERVICE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
